### ISSUE TITLE
Document type names

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_common#23]
As for now the document types are one-letter stings such as "w", "r", etc. See https://github.com/c2corg/v6_common/blob/master/c2corg_common/document_types.py

On the UI side we often have to convert those one-letter code to full typenames such as "waypoints", "routes" etc.

We then have converters, like https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/utils.js#L8-L23

Would it be simpler that the document types are the full typenames everywhere instead of the one-letter code? That would avoid having to make conversions etc.

**Comment by tsauerwein** [comment]
> Would it be simpler that the document types are the full typenames everywhere instead of the one-letter code?

This type is the value of the [discriminator column](http://docs.sqlalchemy.org/en/rel_1_0/orm/inheritance.html#joined-table-inheritance) in the database. I would like to avoid to use a long prose name because it is repeated for every document row.

> On the UI side we often have to convert ...

Currently you have to do it it at 2 places. Is that worth the trouble?
